import os
import logging
from pathlib import Path
import json
from typing import Any

from llama_index.core.workflow import (
    Workflow,
    Context,
    StartEvent,
    StopEvent,
    step,
    Event,
)
from llama_index.llms.openai_like import OpenAILike


# --- Настройка логирования ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("SQLWorkflow")


API_URL = os.getenv("API_URL", "http://192.168.10.22:8110/v1")
API_KEY = os.getenv("API_KEY", "")
LLM_NAME = os.getenv("LLM_NAME", "Qwen3-Coder-30B-A3B-Instruct")

print("API_URL:", API_URL)
print("LLM_NAME:", LLM_NAME)

model = OpenAILike(
   model=LLM_NAME,
   api_base=API_URL,
   api_key="",
   is_function_calling_model=True,
)

ddl_best_practices = Path("api/ddl_best_practices.md").read_text()
sql_best_practices = Path("api/sql_best_practices.md").read_text()

hypotesys_generator_sys_prompt = f"""
You are an expert in analytical SQL queries and data schemas at Trino/Presto. Your task is to analyze the provided DDL table definitions and SQL queries, and then formulate practical, reasonable hypotheses for their improvement.

When generating hypotheses, rely on the following sources of knowledge:
- **Best practices for DDL**:
{ddl_best_practices}

- **Best practices for SQL**:  
{sql_best_practices}

Also consider the features of the DBMS used — **Trino**, including:
- Support for the Parquet format and its limitations,
- Partitioning and bucketing efficiency (if applicable),
- Behavior of functions like `date_trunc', `COALESCE', `UNION ALL`,
- Features of JOINS and aggregations on distributed data.

---

### Output format:
A free list of hypotheses in Markdown format. Every hypothesis should be:
- **Specific** (table, column, design is specified),
- **Reasonable** (why it can improve performance, readability or correctness),
- **Implementable** (a clear action has been proposed: add an index*, change the type, rewrite the subquery, etc.).

 Note: Trino does not support traditional indexes, so instead, offer optimization through schema (partitioning, bucketing, storage format), query restructuring, or denormalization.

Example of the structure:

1. **Hypothesis: Add partitioning by `payment_dt` to the payment tables**  
   The tables `l_payment_client`, `l_excursion_payment` and `l_quest_payment` are actively filtered by date (`payment_dt`). Storing in Parquet without partitioning results in a full scan. It is recommended to recreate tables with `PARTITIONED BY (date_trunc('month', payment_dt))` or a similar strategy.

2. **Hypothesis: Replace `UNION ALL` with duplicate JOINS with a single query with `CASE`**  
   In the request with the ID `27a8890e...` almost identical JOIN chains for excursions and quests are executed twice. Combining into a single query with `CASE WHEN ... THEN 'Excursion' ELSE 'Quest' END` will reduce I/O and execution time.

...

Formulate from **3 to 7 hypotheses**. Don't repeat the general advice — focus on **specifics from the provided DDLs and queries**.
"""

de_sys_prompt = """
You are an experienced **data engineer** specializing in optimizing analytical queries and storage schemes in **Trino**. Your task is to propose **practical improvements** for DDL and SQL based on hypotheses generated by another agent (`hypothesis_agent`).

---

## The work process

1. You will be given:
- The original DDL (one or more `CREATE TABLES'),
- The original SQL query,
- A list of hypotheses from `hypothesis_agent` (in Markdown format).

2. Based on these hypotheses, you should:
   - **Rewrite DDL** if the hypotheses relate to the structure of tables (partitioning, data types, storage format, etc.).
- **Rewrite the SQL query** if the hypotheses relate to logic, JOINS, aggregations, subqueries, etc.
   - Make sure that the result is **syntactically correct** and ** corresponds to the capabilities of Trino**.

3. If the hypotheses **are not applicable** or **do not require changes**, return the original DDL and SQL unchanged.

---

## Output format

You **must** return **strictly valid JSON** with two fields:

```json
{
  "ddl": "Optimized DDL query (CREATE TABLE ...). If there are no changes, the original DDL.",
"sql": "Optimized SQL query. If there are no changes, use the source SQL."
}
``

- Do not add explanations, comments, markdown wrappers.
- Do not use triple quotes, ``json or other frames.
- Make sure that the JSON can be parsed using `json.loads()'.

---

## Restrictions

- Trino **does not support ** indexes, `ALTER TABLE... ADD INDEX` and similar constructions.
- All tables are stored in **Parquet** — keep this in mind when making offers.
- Do not suggest partitioning if there was none in the original DDL, ** unless the hypothesis explicitly requires it**.
- Keep the original names of tables and columns, unless otherwise specified in the hypotheses.

---

## Example of a correct response

```json
{
  "ddl": "CREATE TABLE quests.public.l_payment_client ( client_id integer, payment_id integer, payment_dt timestamp(6), channel varchar, device_type varchar, is_repeat_purchase varchar ) WITH ( format = 'PARQUET', format_version = 2 );",
  "sql": "SELECT sci.registration_source, COUNT(*) AS registered_users, COUNT(sci.first_purchase_date) AS buyers, ROUND(COUNT(sci.first_purchase_date) * 100.0 / COUNT(*), 2) AS conversion_rate FROM quests.public.s_client_personal_info sci GROUP BY sci.registration_source ORDER BY conversion_rate DESC;"
}
```
"""

class HypothesesReadyEvent(Event):
    hypotheses: str


class SQLWorkflow(Workflow):
    @step
    async def generate_hypotheses(
        self, ctx: Context, ev: StartEvent
    ) -> HypothesesReadyEvent:
        ddl = ev.get("ddl")
        sql = ev.get("sql")
        if ddl is None or sql is None:
            raise ValueError("StartEvent must contain 'ddl' and 'sql'")

        await ctx.store.set("original_ddl", ddl)
        await ctx.store.set("original_sql", sql)

        logger.info("🔍 Starting hypothesis generation...")
        logger.info(f"Input DDL:\n{ddl}")
        logger.info(f"Input SQL:\n{sql}")

        prompt = (
            f"{hypotesys_generator_sys_prompt}\n\n"
            f"### Provided DDL:\n{ddl}\n\n"
            f"### Provided SQL:\n{sql}\n\n"
            "Now, generate your hypotheses:"
        )

        hypotheses = await model.acomplete(prompt)
        hypotheses_text = str(hypotheses).strip()

        logger.info("✅ Hypotheses generated:")
        logger.info(hypotheses_text)

        return HypothesesReadyEvent(hypotheses=hypotheses_text)

    @step
    async def optimize_code(
        self, ctx: Context, ev: HypothesesReadyEvent
    ) -> StopEvent:
        original_ddl = await ctx.store.get("original_ddl")
        original_sql = await ctx.store.get("original_sql")

        logger.info("🛠️ Starting code optimization based on hypotheses...")
        logger.info(f"Hypotheses:\n{ev.hypotheses}")

        prompt = (
            f"{de_sys_prompt}\n\n"
            f"DDL:\n{original_ddl}\n\n"
            f"SQL:\n{original_sql}\n\n"
            f"Hypotheses from hypothesis_agent:\n{ev.hypotheses}\n\n"
            "Now, provide your optimized DDL and SQL in the required JSON format:"
        )

        response = await model.acomplete(prompt)
        raw_output = str(response).strip()

        logger.info("🤖 Raw LLM response:")
        logger.info(raw_output)

        # Попытка извлечь JSON
        try:
            start = raw_output.find("{")
            end = raw_output.rfind("}") + 1
            if start != -1 and end != -1:
                json_str = raw_output[start:end]
                logger.debug(f"Extracted JSON string:\n{json_str}")
                result = json.loads(json_str)
                if "ddl" in result and "sql" in result:
                    logger.info("✅ Successfully parsed optimized result")
                    return StopEvent(result=result)
                else:
                    logger.warning("❌ Parsed JSON missing 'ddl' or 'sql' keys")
            else:
                logger.warning("❌ No valid JSON braces found in LLM response")
        except (json.JSONDecodeError, ValueError) as e:
            logger.error(f"❌ JSON parsing failed: {e}")

        # Fallback
        logger.warning("⚠️ Falling back to original DDL and SQL")
        fallback_result = {
            "ddl": original_ddl,
            "sql": original_sql,
        }
        return StopEvent(result=fallback_result)


async def main():
    TEST_DDL = """
    CREATE TABLE quests.public.h_author (
      id integer,
      name varchar,
      created_at timestamp(6)
    ) WITH (format = 'PARQUET', format_version = 2);
    """.strip()

    TEST_SQL = """
    SELECT sci.registration_source, 
           COUNT(*) AS registered_users, 
           COUNT(sci.first_purchase_date) AS buyers, 
           ROUND(COUNT(sci.first_purchase_date) * 100.0 / COUNT(*), 2) AS conversion_rate 
    FROM quests.public.s_client_personal_info sci 
    GROUP BY sci.registration_source 
    ORDER BY conversion_rate DESC;
    """.strip()

    workflow = SQLWorkflow(timeout=120, verbose=True)
    result = await workflow.run(ddl=TEST_DDL, sql=TEST_SQL)
    
    print("\n" + "="*60)
    print("FINAL RESULT:")
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())