import os
from smolagents import CodeAgent, OpenAIModel, tool, ToolCallingAgent
from api.validator import is_sql_valid_trino
from pathlib import Path

API_URL = os.getenv("API_URL")
API_KEY = os.getenv("API_KEY")
LLM_NAME = os.getenv("LLM_NAME")

print(API_URL)
print(LLM_NAME)

model = OpenAIModel(
    model_id=LLM_NAME,
    api_base=API_URL,
    api_key="",
)

ddl_best_practices = Path("api/ddl_best_practices.md").read_text()
sql_best_practices = Path("api/sql_best_practices.md").read_text()

hypotesys_generator_sys_prompt = f"""
You are an expert in analytical SQL queries and data schemas at Trino/Presto. Your task is to analyze the provided DDL table definitions and SQL queries, and then formulate practical, reasonable hypotheses for their improvement.

When generating hypotheses, rely on the following sources of knowledge:
- **Best practices for DDL**:
{ddl_best_practices}

- **Best practices for SQL**:  
{sql_best_practices}

Also consider the features of the DBMS used — **Trino**, including:
- Support for the Parquet format and its limitations,
- Partitioning and bucketing efficiency (if applicable),
- Behavior of functions like `date_trunc', `COALESCE', `UNION ALL`,
- Features of JOINS and aggregations on distributed data.

---

### Output format:
A free list of hypotheses in Markdown format. Every hypothesis should be:
- **Specific** (table, column, design is specified),
- **Reasonable** (why it can improve performance, readability or correctness),
- **Implementable** (a clear action has been proposed: add an index*, change the type, rewrite the subquery, etc.).

 Note: Trino does not support traditional indexes, so instead, offer optimization through schema (partitioning, bucketing, storage format), query restructuring, or denormalization.

Example of the structure:

1. **Hypothesis: Add partitioning by `payment_dt` to the payment tables**  
   The tables `l_payment_client`, `l_excursion_payment` and `l_quest_payment` are actively filtered by date (`payment_dt`). Storing in Parquet without partitioning results in a full scan. It is recommended to recreate tables with `PARTITIONED BY (date_trunc('month', payment_dt))` or a similar strategy.

2. **Hypothesis: Replace `UNION ALL` with duplicate JOINS with a single query with `CASE`**  
   In the request with the ID `27a8890e...` almost identical JOIN chains for excursions and quests are executed twice. Combining into a single query with `CASE WHEN ... THEN 'Excursion' ELSE 'Quest' END` will reduce I/O and execution time.

...

Formulate from **3 to 7 hypotheses**. Don't repeat the general advice — focus on **specifics from the provided DDLs and queries**.
"""

de_sys_prompt = """
You are an experienced **data engineer** specializing in optimizing analytical queries and storage schemes in **Trino**. Your task is to propose **practical improvements** for DDL and SQL based on hypotheses generated by another agent (`hypothesis_agent`).

---

## The work process

1. You will be given:
- The original DDL (one or more `CREATE TABLES'),
- The original SQL query,
- A list of hypotheses from `hypothesis_agent` (in Markdown format).

2. Based on these hypotheses, you should:
   - **Rewrite DDL** if the hypotheses relate to the structure of tables (partitioning, data types, storage format, etc.).
- **Rewrite the SQL query** if the hypotheses relate to logic, JOINS, aggregations, subqueries, etc.
   - Make sure that the result is **syntactically correct** and ** corresponds to the capabilities of Trino**.

3. If the hypotheses **are not applicable** or **do not require changes**, return the original DDL and SQL unchanged.

---

## Output format

You **must** return **strictly valid JSON** with two fields:

```json
{
  "ddl": "Optimized DDL query (CREATE TABLE ...). If there are no changes, the original DDL.",
"sql": "Optimized SQL query. If there are no changes, use the source SQL."
}
``

- Do not add explanations, comments, markdown wrappers.
- Do not use triple quotes, ``json or other frames.
- Make sure that the JSON can be parsed using `json.loads()'.

---

## Restrictions

- Trino **does not support ** indexes, `ALTER TABLE... ADD INDEX` and similar constructions.
- All tables are stored in **Parquet** — keep this in mind when making offers.
- Do not suggest partitioning if there was none in the original DDL, ** unless the hypothesis explicitly requires it**.
- Keep the original names of tables and columns, unless otherwise specified in the hypotheses.

---

## Example of a correct response

```json
{
  "ddl": "CREATE TABLE quests.public.l_payment_client ( client_id integer, payment_id integer, payment_dt timestamp(6), channel varchar, device_type varchar, is_repeat_purchase varchar ) WITH ( format = 'PARQUET', format_version = 2 );",
  "sql": "SELECT sci.registration_source, COUNT(*) AS registered_users, COUNT(sci.first_purchase_date) AS buyers, ROUND(COUNT(sci.first_purchase_date) * 100.0 / COUNT(*), 2) AS conversion_rate FROM quests.public.s_client_personal_info sci GROUP BY sci.registration_source ORDER BY conversion_rate DESC;"
}
```
"""

hypothesis_agent = ToolCallingAgent(
    model=model,
    max_steps=1, 
    tools=[],
    name="hypothesis_agent",
    description="Generates hypotises for ddl and sql optimization"
)

hypothesis_agent.prompt_templates["system_prompt"] = hypotesys_generator_sys_prompt

de_agent = CodeAgent(
    model=model,
    # managed_agents=[hypothesis_agent],
    planning_interval=5,
    verbosity_level=2,
    additional_authorized_imports=["json"],
    # final_answer_checks=[is_sql_valid_trino],
    max_steps=15,
    tools=[]
)

# de_agent.prompt_templates["system_prompt"] = de_sys_prompt

TEST_DDL = """
CREATE TABLE quests.public.h_author (
  id integer,
  name varchar,
  created_at timestamp(6)
) WITH (format = 'PARQUET', format_version = 2);
""".strip()

TEST_SQL = """
SELECT sci.registration_source, 
       COUNT(*) AS registered_users, 
       COUNT(sci.first_purchase_date) AS buyers, 
       ROUND(COUNT(sci.first_purchase_date) * 100.0 / COUNT(*), 2) AS conversion_rate 
FROM quests.public.s_client_personal_info sci 
GROUP BY sci.registration_source 
ORDER BY conversion_rate DESC;
""".strip()

query = f"""
SYSTEM:
{de_sys_prompt}

DDL:
{TEST_DDL}

SQL:
{TEST_SQL}

Optimize it!!!
"""

result = de_agent.run(query)
print(result)